---
title: "IGCSimulationSummary"
author: "Xiang Ji"
date: "January 18, 2016"
output: html_document
---

This script is used for summarizing IGC Simulation result (with tract length)

Read in data first
```{r}
rm(list=ls())  # clean up workspace
IGC.path <- "/Users/xji3/FromCluster_IGCSimulation_01172016/"
IGC.x3.path <- "/Users/xji3/FromCluster_IGCSimulation_multiply3_01172016/"
IGC.geo.list <- c(1.0, 10.0, 50.0, 100.0, 500.0)
#IGC.geo.list <- c(1.0)
num.sim = 100
paralog = "YDR418W_YEL054C"

#Read.summary <- function(IGC.path, IGC.x3.path, IGC.geo.list, num.sim = 100, paralog = "YDR418W_YEL054C"){
## Now read simulation result

sim.path <- paste("SimulationSummary", paralog, "",sep = "/")
for (IGC.geo in IGC.geo.list){
  summary_mat <- NULL
  IGC.geo.path <- paste("IGCgeo_", toString(IGC.geo), ".0/", sep = "")
  file.prefix <- paste(paralog, "MG94_geo", paste(toString(IGC.geo), ".0", sep = ""), "Sim", sep = "_")
  file.suffix <- "summary.txt"
  for (sim.num in 0:(num.sim - 1)){
    file.name <- paste(file.prefix, toString(sim.num), file.suffix, sep = "_")
    summary_file <- paste(IGC.path, sim.path, IGC.geo.path, file.name, sep = "")
    if (file.exists(summary_file)){
      all <- readLines(summary_file, n = -1)
      col.names <- paste("geo", paste(toString(IGC.geo), ".0", sep = ""), "sim", toString(sim.num), sep = "_")
      row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
      summary_mat <- cbind(summary_mat, as.matrix(read.table(summary_file, 
                                                             row.names = row.names, 
                                                             col.names = col.names)))        
      }
    }
  assign(paste("geo", paste(toString(IGC.geo), ".0", sep = ""), "summary", sep = "_"), summary_mat)
  }


## Now read multiply 3 simulation result

sim.x3.path <- paste("SimulationSummary_multiply3", paralog, "",sep = "/")
for (IGC.geo in IGC.geo.list){
  summary_mat <- NULL
  IGC.geo.path <- paste("IGCgeo_", toString(IGC.geo), ".0/", sep = "")
  file.prefix <- paste(paralog, "MG94_geo", paste(toString(IGC.geo), ".0", sep = ""), "Sim", sep = "_")
  file.suffix <- "summary.txt"
  for (sim.num in 0:(num.sim - 1)){
    file.name <- paste(file.prefix, toString(sim.num), file.suffix, sep = "_")
    summary_file <- paste(IGC.x3.path, sim.x3.path, IGC.geo.path, file.name, sep = "")
    if (file.exists(summary_file)){
      all <- readLines(summary_file, n = -1)
      col.names <- paste("geo", paste(toString(IGC.geo), ".0", sep = ""), "sim", toString(sim.num), sep = "_")
      row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
      summary_mat <- cbind(summary_mat, as.matrix(read.table(summary_file, 
                                                             row.names = row.names, 
                                                             col.names = col.names)))        
      
      }
    
    }
  assign(paste("geo", paste(toString(IGC.geo), ".0", sep = ""), "x3_summary", sep = "_"), summary_mat)
  }
```

Now analyze the simulation results

parameters used in generating datasets are:

pi_a = 0.2983654, pi_c = 0.2095729, pi_g = 0.1871536, pi_t = 0.3049081 

kappa = 8.4043336

omega = 0.0761853

tau = 1.409408  (0.42)

Tau estimate summary

```{r}
# geo_1.0
summary(geo_1.0_x3_summary["tau", ])
sd(geo_1.0_x3_summary["tau", ])
# geo_10.0
summary(geo_10.0_x3_summary["tau", ])
sd(geo_10.0_x3_summary["tau", ])
# geo_50.0
summary(geo_50.0_x3_summary["tau", ])
sd(geo_50.0_x3_summary["tau", ])
# geo_100.0
summary(geo_100.0_x3_summary["tau", ])
sd(geo_100.0_x3_summary["tau", ])
# geo_500.0
summary(geo_500.0_x3_summary["tau", ])
sd(geo_500.0_x3_summary["tau", ])

sd.list <- c(sd(geo_1.0_x3_summary["tau", ]), sd(geo_10.0_x3_summary["tau", ]),
             sd(geo_50.0_x3_summary["tau", ]), sd(geo_100.0_x3_summary["tau", ]),
             sd(geo_500.0_x3_summary["tau", ]))
plot(IGC.geo.list, sd.list)
abline(h = 0.42)

mean.list <- c(mean(geo_1.0_x3_summary["tau", ]), mean(geo_10.0_x3_summary["tau", ]),
             mean(geo_50.0_x3_summary["tau", ]), mean(geo_100.0_x3_summary["tau", ]),
             mean(geo_500.0_x3_summary["tau", ]))
plot(IGC.geo.list, mean.list)
abline(h = 1.409408)
```

Now summarized % changes due to IGC in simulation estimates

It was estimated 0.2131 (0.02884)
```{r}
percent.IGC.geo.1.0 <- colSums(geo_1.0_x3_summary[34:45, ] + geo_1.0_x3_summary[46:57, ]) / (colSums(geo_1.0_x3_summary[34:45, ] + geo_1.0_x3_summary[46:57, ] + geo_1.0_x3_summary[58:69, ]))
summary(percent.IGC.geo.1.0)
sd(percent.IGC.geo.1.0)

percent.IGC.geo.10.0 <- colSums(geo_10.0_x3_summary[34:45, ] + geo_10.0_x3_summary[46:57, ]) / (colSums(geo_10.0_x3_summary[34:45, ] + geo_10.0_x3_summary[46:57, ] + geo_10.0_x3_summary[58:69, ]))
summary(percent.IGC.geo.10.0)
sd(percent.IGC.geo.10.0)

percent.IGC.geo.50.0 <- colSums(geo_50.0_x3_summary[34:45, ] + geo_50.0_x3_summary[46:57, ]) / (colSums(geo_50.0_x3_summary[34:45, ] + geo_50.0_x3_summary[46:57, ] + geo_50.0_x3_summary[58:69, ]))
summary(percent.IGC.geo.50.0)
sd(percent.IGC.geo.50.0)

percent.IGC.geo.100.0 <- colSums(geo_100.0_x3_summary[34:45, ] + geo_100.0_x3_summary[46:57, ]) / (colSums(geo_100.0_x3_summary[34:45, ] + geo_100.0_x3_summary[46:57, ] + geo_100.0_x3_summary[58:69, ]))
summary(percent.IGC.geo.100.0)
sd(percent.IGC.geo.100.0)

percent.IGC.geo.500.0 <- colSums(geo_500.0_x3_summary[34:45, ] + geo_500.0_x3_summary[46:57, ]) / (colSums(geo_500.0_x3_summary[34:45, ] + geo_500.0_x3_summary[46:57, ] + geo_500.0_x3_summary[58:69, ]))
summary(percent.IGC.geo.500.0)
sd(percent.IGC.geo.500.0)

# plot mean % changes due to IGC v.s. IGC_geo
mean.percent.IGC.list <- c(mean(percent.IGC.geo.1.0), mean(percent.IGC.geo.10.0), 
                     mean(percent.IGC.geo.50.0), mean(percent.IGC.geo.100.0),
                     mean(percent.IGC.geo.500.0))
plot(IGC.geo.list, mean.percent.IGC.list)
abline(h = 0.2131)

sd.percent.IGC.list <- c(sd(percent.IGC.geo.1.0), sd(percent.IGC.geo.10.0), 
                     sd(percent.IGC.geo.50.0), sd(percent.IGC.geo.100.0),
                     sd(percent.IGC.geo.500.0))

plot(IGC.geo.list, sd.percent.IGC.list)
abline(h = 0.02884)
```